"""Writes the Equalizer APO config. Never changes audio defaults or security policy."""
from __future__ import annotations

import hashlib
import os
from pathlib import Path

from .devices import endpoint_guid
from .model import effective_preamp, normalize_state, response_samples
from .storage import atomic_text
from . import compression, limiter, space

BEGIN = '# BEGIN R7-EQ'
END = '# END R7-EQ'
INCLUDE = 'Include: r7-eq.txt'
BLOCK = f'{BEGIN}\nStage: post-mix\nDevice: all\n{INCLUDE}\n{END}'
# The audio engine (audiodg) runs as LOCAL SERVICE; it loads plugins only if one of these can read them.
AUDIO_SERVICE_SIDS = ('S-1-5-19', 'S-1-5-6', 'S-1-5-11', 'S-1-5-32-545', 'S-1-1-0')
PLUGIN_ACCESS_WARNING = ('Windows audio cannot read the r7-EQ plugins folder, so compression, Space '
                         'and the clip guard are not running. Grant LOCAL SERVICE read access to it.')


def audio_service_can_read(path):
    """Equalizer APO silently skips a plugin the audio service can't read."""
    if os.name != 'nt':
        return True
    import ctypes
    from ctypes import wintypes

    class Trustee(ctypes.Structure):
        _fields_ = [('multiple', ctypes.c_void_p), ('operation', ctypes.c_int), ('form', ctypes.c_int),
                    ('type', ctypes.c_int), ('sid', ctypes.c_void_p)]

    advapi = ctypes.WinDLL('advapi32')
    kernel = ctypes.WinDLL('kernel32')
    kernel.LocalFree.argtypes = (ctypes.c_void_p,)
    dacl, descriptor = ctypes.c_void_p(), ctypes.c_void_p()
    # SE_FILE_OBJECT, DACL_SECURITY_INFORMATION
    error = advapi.GetNamedSecurityInfoW(str(path), 1, 4, None, None, ctypes.byref(dacl), None,
                                         ctypes.byref(descriptor))
    if error:
        raise OSError(error, f'Cannot read permissions of {path}')
    try:
        for text in AUDIO_SERVICE_SIDS:
            sid = ctypes.c_void_p()
            if not advapi.ConvertStringSidToSidW(text, ctypes.byref(sid)):
                continue
            try:
                mask = wintypes.DWORD()
                trustee = Trustee(None, 0, 0, 0, sid)   # NO_MULTIPLE_TRUSTEE, TRUSTEE_IS_SID
                if not advapi.GetEffectiveRightsFromAclW(dacl, ctypes.byref(trustee), ctypes.byref(mask)) \
                        and mask.value & 0x21 == 0x21:   # FILE_READ_DATA | FILE_EXECUTE
                    return True
            finally:
                kernel.LocalFree(sid)
        return False
    finally:
        kernel.LocalFree(descriptor)


def installation():
    if os.name != 'nt':
        return None
    import winreg
    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, r'SOFTWARE\EqualizerAPO', 0,
                            winreg.KEY_READ | winreg.KEY_WOW64_64KEY) as key:
            root = Path(winreg.QueryValueEx(key, 'InstallPath')[0])
            try:
                config = Path(winreg.QueryValueEx(key, 'ConfigPath')[0])
            except FileNotFoundError:
                config = root / 'config'
            return {'root': root, 'config': config}
    except FileNotFoundError:
        return None


def device_lines(profile):
    state = normalize_state(profile.state)
    lines = [f'Device: {endpoint_guid(profile.endpoint_id)}', 'Channel: L R']
    if state['enabled']:
        preamp = effective_preamp(state)
        if abs(preamp) > 0.000001:
            lines.append(f'Preamp: {preamp:.4f} dB')
        samples = response_samples(state, tolerance=0.02)
        if any(abs(gain) > 0.00001 for _, gain in samples):
            lines.append('GraphicEQ: ' + '; '.join(f'{hz:.6f} {gain:.6f}' for hz, gain in samples))
    else:
        lines.append('# EQ bypassed: no r7-EQ filters or gain applied.')
    lines.extend(compression.config_lines(state, profile.slot))
    if state['enabled']:  # Space is character, like the curve: the EQ switch bypasses it.
        lines.extend(space.config_lines(state))
    lines.extend(limiter.config_lines(state))   # Always last: nothing after it can clip.
    return lines


def compile_config(profiles, power=True):
    """Devices without a section play untouched."""
    lines = ['# Generated by r7-EQ, edits here are overwritten.', 'Stage: post-mix']
    if not power:
        lines.append('# r7-EQ is switched off: every device plays untouched.')
        profiles = []
    for profile in sorted(profiles, key=lambda profile: profile.slot):
        lines.extend(device_lines(profile))
    return '\n'.join(lines) + '\n'


class ApoBackend:
    def __init__(self, config_directory=None):
        self._override = Path(config_directory) if config_directory is not None else None
        self._last_digest = ''

    def config_directory(self):
        if self._override is not None:
            return self._override
        found = installation()
        return found['config'] if found else None

    def status(self):
        directory = self.config_directory()
        if directory is None:
            return 'warning', 'Equalizer APO is not installed, edits are saved locally'
        root = directory / 'config.txt'
        if not root.exists():
            return 'warning', 'Equalizer APO configuration is missing'
        text = root.read_text(encoding='utf-8-sig')
        if BLOCK not in text or text.count(BEGIN) != 1 or text.count(END) != 1:
            return 'warning', 'r7-EQ is not connected to Equalizer APO, edits are saved locally'
        return 'info', 'Connected to Equalizer APO configuration'

    def apply(self, profiles, power=True):
        """A section for an absent device is harmless."""
        profiles = list(profiles)
        severity, message = self.status()
        if severity != 'info':
            return severity, message, False
        for profile in profiles:
            state = normalize_state(profile.state)
            if state['compressor'] and not compression.LIBRARY.is_file():
                raise RuntimeError(f'Compression plugin missing: {compression.LIBRARY}; audio config unchanged')
            if state['enabled'] and space.config_lines(state) and not space.LIBRARY.is_file():
                raise RuntimeError(f'Space plugin missing: {space.LIBRARY}; audio config unchanged')
            if limiter.needed(state) and not limiter.LIBRARY.is_file():
                raise RuntimeError(f'Limiter plugin missing: {limiter.LIBRARY}; audio config unchanged')
        text = compile_config(profiles, power)
        unreadable = 'VSTPlugin:' in text and not all(
            audio_service_can_read(library) for library in (compression.LIBRARY, space.LIBRARY, limiter.LIBRARY) if library.is_file())
        digest = hashlib.sha256(text.encode('utf-8')).hexdigest()
        path = self.config_directory() / 'r7-eq.txt'
        if path.is_symlink():
            raise RuntimeError('r7-eq.txt is a link, not changed')
        # Avoid rewriting identical data, but notice externally changed output.
        if digest != self._last_digest or not path.exists() or path.read_text(encoding='utf-8') != text:
            atomic_text(path, text)
            self._last_digest = digest
            changed = True
        else:
            changed = False
        if unreadable:
            return 'warning', PLUGIN_ACCESS_WARNING, changed
        return 'info', 'Saved to Equalizer APO' if power else 'r7-EQ is off: every device plays untouched', changed

    def attach(self, profiles, power=True):
        """Runs once, for the first device: adds an include to config.txt and keeps the original."""
        directory = self.config_directory()
        if directory is None:
            raise RuntimeError('Equalizer APO is not installed')
        root = directory / 'config.txt'
        if root.is_symlink() or (directory / 'r7-eq.txt').is_symlink():
            raise RuntimeError('config.txt or r7-eq.txt is a link, not changed')
        original = root.read_text(encoding='utf-8-sig')
        if BEGIN in original or END in original:
            if BLOCK not in original or original.count(BEGIN) != 1 or original.count(END) != 1:
                raise RuntimeError('config.txt already has a different r7-EQ block, left unchanged')
            return self.apply(profiles, power)
        backup = directory / 'config.before-r7-eq.txt'
        if backup.exists():
            raise RuntimeError(f'{backup.name} already exists, left unchanged')
        generated = directory / 'r7-eq.txt'
        if generated.exists():
            raise RuntimeError('r7-eq.txt already exists, left unchanged')
        atomic_text(backup, original)
        atomic_text(generated, compile_config(profiles, power))
        # Append only: existing APO configuration and ordering are preserved.
        atomic_text(root, original.rstrip() + f'\n\n{BLOCK}\n')
        return 'info', 'Connected to Equalizer APO', True
